name: reviewdog

on: [pull_request]

jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review